[package]
name = "tideloom-core"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde_json = "1"
tideloom = { path = ".." }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
